#!/bin/bash

set -eo pipefail

cd $RUNNER_TEMP

mkdir -p .setup-riscv-gnu-toolchain
pushd .setup-riscv-gnu-toolchain
if [ -n "$1" ]; then
    build=`curl -s https://api.github.com/repos/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/tags/$1 | grep browser_download_url | grep linux-x64 | grep -v sha | cut -f4 -d\"`
else
    build=`curl -s https://api.github.com/repos/xpack-dev-tools/riscv-none-embed-gcc-xpack/releases/latest | grep browser_download_url | grep linux-x64 | grep -v sha | cut -f4 -d\"`
fi
wget -q $build -O build.tgz
tar xfz build.tgz --strip-components=1
rm build.tgz
popd
